import type { DatagridDefinition } from '../../../common/datagrid';

export const MEETINGS_DATAGRID: DatagridDefinition = {
  resource: 'meetings',
  searchable: true,
  searchPlaceholderKey: 'datagrid.meetings.search',
  defaultSort: { key: 'startedAt', dir: 'desc' },
  columns: [
    {
      key: 'title',
      labelKey: 'datagrid.meetings.columns.title',
      type: 'text',
      sortable: true,
      sortField: 'title',
    },
    {
      key: 'host',
      field: 'hostName',
      labelKey: 'datagrid.meetings.columns.host',
      type: 'text',
      sortable: true,
      sortField: 'host.name',
    },
    {
      key: 'participants',
      field: 'participantCount',
      labelKey: 'datagrid.meetings.columns.participants',
      type: 'number',
      sortable: true,
      sortField: 'participants._count',
      align: 'right',
      hideBelow: 'md',
    },
    {
      key: 'messages',
      field: 'messageCount',
      labelKey: 'datagrid.meetings.columns.messages',
      type: 'number',
      sortable: true,
      sortField: 'messages._count',
      align: 'right',
      hideBelow: 'lg',
    },
    { key: 'status', labelKey: 'datagrid.meetings.columns.status', type: 'badge', sortable: false },
    {
      key: 'startedAt',
      labelKey: 'datagrid.meetings.columns.startedAt',
      type: 'datetime',
      sortable: true,
      sortField: 'startedAt',
      hideBelow: 'sm',
    },
    {
      key: 'actions',
      labelKey: 'datagrid.meetings.columns.actions',
      type: 'custom',
      sortable: false,
      align: 'right',
    },
  ],
  filters: [
    {
      key: 'status',
      labelKey: 'datagrid.meetings.filters.status.label',
      type: 'select',
      options: [
        { value: 'WAITING', labelKey: 'datagrid.meetings.filters.status.WAITING' },
        { value: 'ACTIVE', labelKey: 'datagrid.meetings.filters.status.ACTIVE' },
        { value: 'ENDED', labelKey: 'datagrid.meetings.filters.status.ENDED' },
      ],
    },
  ],
  actions: [
    {
      key: 'view',
      labelKey: 'datagrid.meetings.actions.view',
      icon: 'eye',
      scope: 'row',
      permission: 'meetings.view',
    },
    {
      key: 'end',
      labelKey: 'datagrid.meetings.actions.end',
      icon: 'phone-off',
      style: 'danger',
      confirm: true,
      scope: 'row',
      permission: 'meetings.force-end',
    },
    {
      key: 'delete',
      labelKey: 'datagrid.meetings.actions.delete',
      icon: 'trash',
      style: 'danger',
      confirm: true,
      scope: 'row',
      permission: 'meetings.delete',
    },
    {
      key: 'end-all',
      labelKey: 'datagrid.meetings.actions.end-all',
      icon: 'phone-off',
      style: 'danger',
      confirm: true,
      scope: 'bulk',
      permission: 'meetings.force-end',
    },
  ],
};
