configure_env_files() {
  step "Configuring environment files"

  local f
  for f in "$SERVER_ENV" "$WEB_ENV" "$ADMIN_ENV" "$ROOT_ENV"; do
    if [ -e "$f" ] && [ ! -w "$f" ]; then
      die "$f exists but is not writable by $(whoami). Fix ownership (sudo chown \"\$(id -un)\" $f) or remove it, then re-run."
    fi
  done

  if [ ! -f "$SERVER_ENV" ] || [ "$FORCE" = true ]; then
    _generate_env_files
  else
    ok "Kept existing env files (use --force to regenerate)"
    _ensure_env_targets
  fi

  set_env "$SERVER_ENV" LIVEKIT_API_KEY "$LIVEKIT_KEY_NAME"

  _sync_root_env
}

_generate_env_files() {
  [ "$FORCE" = true ] && [ -f "$SERVER_ENV" ] && warn "Overwriting existing env files (--force)."

  local pair
  for pair in "${ENV_FILES[@]}"; do
    copy_env_file "${pair%%|*}" "${pair##*|}"
  done

  local key
  for key in "${GENERATED_SECRET_KEYS[@]}"; do
    set_env "$SERVER_ENV" "$key" "$(gen_secret)"
  done
  ok "Generated JWT + LiveKit secrets into $SERVER_ENV"
}

# Create any app env file that doesn't exist yet (e.g. a newly added app like
# admin) from its template, leaving env files that already exist untouched.
_ensure_env_targets() {
  local pair dest
  for pair in "${ENV_FILES[@]}"; do
    dest="${pair##*|}"
    [ -f "$dest" ] || copy_env_file "${pair%%|*}" "$dest"
  done
}

_sync_root_env() {
  # Root .env feeds docker compose interpolation only; mirror the server creds.
  local lk_key lk_secret
  lk_key="$(read_env "$SERVER_ENV" LIVEKIT_API_KEY)"
  lk_secret="$(read_env "$SERVER_ENV" LIVEKIT_API_SECRET)"
  [ -n "$lk_secret" ] || die "LIVEKIT_API_SECRET missing from $SERVER_ENV."

  cat >"$ROOT_ENV" <<EOF
# Generated by setup.sh - consumed by docker compose interpolation only. Do not commit.
LIVEKIT_API_KEY=${lk_key}
LIVEKIT_API_SECRET=${lk_secret}
EOF
  ok "Synced $ROOT_ENV for docker compose (key name: $lk_key)"
}
