import type { DatagridDefinition } from '../../../common/datagrid';

export const USERS_DATAGRID: DatagridDefinition = {
  resource: 'users',
  searchable: true,
  searchPlaceholderKey: 'datagrid.users.search',
  defaultSort: { key: 'createdAt', dir: 'desc' },
  columns: [
    {
      key: 'name',
      labelKey: 'datagrid.users.columns.name',
      type: 'text',
      sortable: true,
      sortField: 'name',
    },
    {
      key: 'email',
      labelKey: 'datagrid.users.columns.email',
      type: 'text',
      sortable: true,
      sortField: 'email',
    },
    {
      key: 'meetingsHosted',
      labelKey: 'datagrid.users.columns.meetingsHosted',
      type: 'number',
      sortable: true,
      sortField: 'hostedMeetings._count',
      align: 'right',
      hideBelow: 'md',
    },
    {
      key: 'meetingsAttended',
      labelKey: 'datagrid.users.columns.meetingsAttended',
      type: 'number',
      sortable: true,
      sortField: 'meetings._count',
      align: 'right',
      hideBelow: 'md',
    },
    {
      key: 'canCreateGroups',
      labelKey: 'datagrid.users.columns.canCreateGroups',
      type: 'boolean',
      sortable: true,
      sortField: 'canCreateGroups',
      hideBelow: 'lg',
    },
    {
      key: 'createdAt',
      labelKey: 'datagrid.users.columns.createdAt',
      type: 'datetime',
      sortable: true,
      sortField: 'createdAt',
      hideBelow: 'sm',
    },
    {
      key: 'actions',
      labelKey: 'datagrid.users.columns.actions',
      type: 'custom',
      sortable: false,
      align: 'right',
    },
  ],
  actions: [
    {
      key: 'create',
      labelKey: 'datagrid.users.actions.create',
      icon: 'plus',
      style: 'primary',
      scope: 'toolbar',
      permission: 'users.create',
    },
    {
      key: 'invite',
      labelKey: 'datagrid.users.actions.invite',
      icon: 'mail',
      scope: 'toolbar',
      permission: 'users.invite',
    },
    {
      key: 'edit',
      labelKey: 'datagrid.users.actions.edit',
      icon: 'pencil',
      scope: 'row',
      permission: 'users.update',
    },
    {
      key: 'toggle-chat',
      labelKey: 'datagrid.users.actions.toggleChat',
      icon: 'message-square-off',
      scope: 'row',
      permission: 'users.update',
    },
    {
      key: 'delete',
      labelKey: 'datagrid.users.actions.delete',
      icon: 'trash',
      style: 'danger',
      confirm: true,
      scope: 'row',
      permission: 'users.delete',
    },
  ],
};
