export interface ApiSuccess<TData> {
  success: true;
  data: TData;
  meta?: ApiMeta;
}

export interface ApiError {
  success: false;
  error: {
    code: string;
    message: string;
    statusCode: number;
    details?: unknown;
  };
}

export type ApiResponse<TData> = ApiSuccess<TData> | ApiError;

export interface ApiMeta {
  timestamp: string;
  page?: number;
  pageSize?: number;
  total?: number;
}

export const ApiErrorCode = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  UNAUTHORIZED: 'UNAUTHORIZED',
  EMAIL_TAKEN: 'EMAIL_TAKEN',

  MEETING_NOT_FOUND: 'MEETING_NOT_FOUND',
  MEETING_ENDED: 'MEETING_ENDED',
  MEETING_FORBIDDEN: 'MEETING_FORBIDDEN',
  ALREADY_JOINED: 'ALREADY_JOINED',

  RECORDING_NOT_FOUND: 'RECORDING_NOT_FOUND',
  RECORDING_ALREADY_ACTIVE: 'RECORDING_ALREADY_ACTIVE',
  RECORDING_NOT_ACTIVE: 'RECORDING_NOT_ACTIVE',
  RECORDING_FAILED: 'RECORDING_FAILED',

  CHAT_FORBIDDEN: 'CHAT_FORBIDDEN',
  CONVERSATION_NOT_FOUND: 'CONVERSATION_NOT_FOUND',
  NOT_TEAMMATES: 'NOT_TEAMMATES',
  CHAT_DISABLED: 'CHAT_DISABLED',
  GROUPS_DISABLED: 'GROUPS_DISABLED',
  NOT_GROUP_ADMIN: 'NOT_GROUP_ADMIN',
  LAST_ADMIN: 'LAST_ADMIN',
  MESSAGE_NOT_FOUND: 'MESSAGE_NOT_FOUND',
  POLL_NOT_FOUND: 'POLL_NOT_FOUND',
  POLL_CLOSED: 'POLL_CLOSED',
  INVITE_INVALID: 'INVITE_INVALID',
  INVITE_EXPIRED: 'INVITE_EXPIRED',

  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_NAME_TAKEN: 'ROLE_NAME_TAKEN',
  ROLE_IS_SYSTEM: 'ROLE_IS_SYSTEM',
  ROLE_HAS_MEMBERS: 'ROLE_HAS_MEMBERS',
  ROLE_PERMISSION_INVALID: 'ROLE_PERMISSION_INVALID',

  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  CONFLICT: 'CONFLICT',
} as const;

export type ApiErrorCode = (typeof ApiErrorCode)[keyof typeof ApiErrorCode];
